/*
 * File: resources/js/faculty/ai/prompts.js
 * Description: Per-partial guidance prompts for the syllabus AI.
 */
(function(){
	'use strict';

	// Keyed by syllabus partial key (data-partial-key)
	const PROMPTS = {
		'__global_information': (
			'Important: Always prioritize what the faculty member explicitly types or selects on the syllabus page. ' +
			'Use institutional templates, course snapshots, and any default text only as supporting references, not as replacements for the user\'s intent. ' +
			'If there is a conflict between a template and the instructor\'s own wording, follow the instructor\'s wording and offer suggestions in a respectful, optional way (never overwrite their voice).' 
		),
		'course-rationale': (
			'The Course Rationale and Description field is a concise, well-written narrative that explains why the course exists, what it focuses on, and how it supports the program and institutional goals (including ILOs, IGA, SO, CDIO, and SDG where relevant). It should be grounded in the actual course title, code, category, level, and outcomes in the snapshots, and it must use professional, student-centered language. When you generate this, use all available context (course information, ILOs, assessment methods, TLA strategies, and mappings) to craft a single integrated paragraph or two that: (1) states the overall purpose and scope of the course, (2) highlights key knowledge and skills students will develop, and (3) briefly notes how the course contributes to graduate/program outcomes and institutional directions. Output your answer as one continuous narrative only (plain text, no markdown table and no bullet list), exactly as it should appear in the Course Rationale and Description field. Do not invent course details that clearly conflict with the snapshots; when in doubt, stay general but still meaningful.'
		),
		'mission-vision': (
			'These are the official Vision and Mission of Batangas State University ARASOF TNEU. ' +
			'Vision: "A premier national university that develops leaders in the global knowledge economy." ' +
			'Mission: "A university committed to producing leaders by providing a 21st century learning environment through innovations in education, multidisciplinary research, and community and industry partnerships in order to nurture the spirit of nationhood, propel the national economy and engage the world for sustainable development." ' +
			'When assisting with this section, do not alter the official wording of the Vision and Mission. ' +
			'You may, however, explain, contextualize, or suggest how the course outcomes, activities, and assessments align with these statements in clear, concise, and professional language. ' +
			'When the Vision and Mission are restated or highlighted in your reply, they are typically shown as a simple bulleted list (for example: • Vision: … • Mission: …) to make them visually clear and easy to scan.'
		),
		'course-info': (
			'This section presents the core Course Information as it appears on the official CIS form. It includes basic identifiers (Course Title, Course Code, Course Category, Pre‑requisite/s), scheduling and credit details (Semester, Year Level, Credit Hours, Period of Study, Revision Date, Contact Hours), and instructor information (Instructor Name, Employee No., Designation, Email, Date Prepared), together with the Reference CMO and the current Revision No. The Course Rationale and Description field provides a narrative summary of the course focus, scope, and purpose, written in clear, professional language that is consistent with the program and institutional context. Entries in this section are factual, concise, and formatted to match institutional conventions; values are derived from the syllabus data provided by the faculty member and should not introduce new information beyond what is present in the snapshots and fields. When you summarize or restate the course information in your reply, present it as a clean bulleted list of key fields and values (for example: • Course Title: … • Course Code: … • Semester / Year Level: …) so that the instructor can quickly scan and verify each detail.'
		),
		'criteria-assessment': (
			'This section presents the assessment scheme for the course. Assessment is organized into CATEGORIES (for example: Quizzes, Major Exams, Projects, Laboratory Work, Class Participation), each with its own overall percentage contribution to the final grade. Within each category are specific TASKS (such as Quiz 1, Quiz 2, Midterm Exam, Final Project) with sub‑percentages and brief descriptions. The total of all category percentages is expected to be 100%, and for each category the combined percentage of its tasks matches that category\'s overall weight. Wording of criteria typically uses professional, parallel, and measurable phrasing (e.g., "Demonstrates", "Applies", "Analyzes") and is aligned with the stated course outcomes and institutional grading policies. When you summarize or restate this section, present it using a fixed markdown table structure with the header row "| Category | Assessment | Percent |" followed by the alignment row "|:--|:--|:--|" and then one row per task. For groups of tasks that belong to the same category, write the category name in the first row only and leave the "Category" cell blank on the following rows, so that the category is not visually duplicated for every task. In each row, put the specific task name or short description under "Assessment", and the numeric weight or percentage (without extra commentary) under "Percent" so that the whole scheme is easy to read at a glance.'
		),
		'tlas': (
			'The Teaching, Learning, and Assessment Strategies section describes how the course is actually delivered and how students engage with the material. It typically includes a mix of direct instruction (for example, lectures explaining major concepts and principles, often supported by practical examples), interactive learning (discussion, questioning, and other activities that let students organize ideas, share perspectives, and practice communicating clearly), and technology‑enhanced approaches such as Computer‑Assisted Instruction and Computer‑Assisted Learning using multimedia presentations and tools like Google Classroom, Google Meet, and shared online resources. Consultation hours and informal channels (email, group chat, online platforms) provide additional support, while collaborative learning (small groups working on shared topics or tasks) encourages teamwork and peer learning. In many syllabi, this narrative also connects strategies to assessment practices, noting that students may be evaluated through combinations of written and oral examinations, quizzes and chapter tests, hybrid or blended learning activities, tutorials, laboratory work, self‑directed learning, web‑based research, reports, projects, portfolios, and rubric‑based evaluation of laboratory and project outputs.'
		),
		'ilo': (
			'The Intended Learning Outcomes (ILO) section states what students are expected to know, understand, and be able to do after successfully completing this course. Each row in this partial has two main parts: (1) an ILO code (for example: ILO1, ILO2, ILO3) that serves as a concise label, and (2) a corresponding description that explains the specific outcome in clear, measurable language. Descriptions typically combine an action verb, the content or skill focus, and, when relevant, conditions or standards (for example: "Explain the fundamental concepts of …", "Apply appropriate methods to …", "Design and evaluate …"). The set of ILO codes and descriptions together forms the official list of learning outcomes for the course and provides the reference point for aligning teaching strategies, learning activities, and assessment tasks. When you generate or restate the ILO section, output a single fixed markdown table only (no extra narrative before or after the table) with the header row "| Code | Description |" followed by the alignment row "|:--|:--|" and then one row per ILO, placing the ILO code under "Code" and the full outcome statement under "Description". If the snapshot shows that there are no ILOs defined (for example, there are zero ILO rows or only a placeholder message), do not invent any outcomes and do not echo the placeholder snapshot text; instead, reply briefly to the user to say that no Intended Learning Outcomes are currently defined and that they should add ILOs on the syllabus page first.'
		),
		'assessment-tasks-distribution': (
			'The Assessment Method and Distribution Map section gives a detailed breakdown of how individual assessment tasks contribute to the course grade and how they align with the ILOs and learning domains. The CODE column holds short labels for tasks or categories (for example: Q, Qz, ME for Midterm Exam, FE for Final Exam, PRJ for Project), chosen by the instructor. The ASSESSMENT TASK column lists assessment categories and the specific tasks under each category (for example, a category such as "Quizzes" with tasks like "Quiz 1", "Quiz 2", or a category such as "Exams" with tasks like "Midterm Exam" and "Final Exam"). The I/R/D column indicates the role of each task in the learning sequence: I (Introduction), R (Reinforcement), or D (Deliverable/output), with some tasks possibly marked as combinations (such as I/D) depending on how the instructor uses them. The PERCENTAGE column records the percentage weight of the category or individual task in the grading scheme. The ILO columns list ILO codes in order (ILO1, ILO2, etc.), and the entries in these cells are numbers representing how many items or components of the task are aligned to each ILO. The C, P, and A columns summarize the distribution of total items or components across Cognitive Knowledge (C), Psychomotor Skill (P), and Affective/Appreciative (A) aspects; for example, a Midterm Exam with 70 items may have "70" entered under C to indicate strong emphasis on cognitive outcomes, while a Project might be recorded with values in both C and P to show a mix of knowledge and practical performance. Totals in the ILO columns correspond to how items are mapped across outcomes, and totals in C/P/A reflect the overall character of each assessment task. When you summarize or restate this section, present it using a fixed markdown table structure that starts with the header row "| Code | Task | I/R/D | % | ILO1 | ILO2 | … | C | P | A |" (using as many ILO columns as are needed and then C, P, A at the end), followed by an alignment row with ":--" for each column. Use one row for each main task or category, and, if you include subtasks, indent their names under the "Task" column (for example, "- Quiz 1") so that the structure remains clear.'
		),
		'iga': (
			'The Institutional Graduate Attributes (IGA) section summarizes the qualities and capabilities that students are expected to have developed by the time they graduate from the institution. Each row in this partial has three parts: (1) an IGA code (for example: IGA1, IGA2, IGA3) that serves as a short, stable label; (2) a brief title that names the attribute in a compact way (for example, "Knowledge Competence", "Communication Skills", or "Ethical Leadership"); and (3) a fuller description that explains the attribute in sentence form, such as "Demonstrate a mastery of the fundamental knowledge and skills required for functioning effectively as a professional in the discipline, and an ability to integrate and apply them effectively to practice in the workplace." The descriptions typically state what a graduate knows, can do, or demonstrates in that area. Together, these IGA codes, titles, and descriptions represent the institution-wide outcomes for graduates and provide a reference point for aligning program outcomes, course ILOs, and assessment practices. When you summarize or restate the IGA section, present it as a fixed markdown table with the header row "| Code | Title | Description |" followed by the alignment row "|:--|:--|:--|" and then one row per IGA, placing the IGA code, short title, and full description in their respective columns.'
		),
		'so': (
			'The Student Outcomes (SO) section lists the specific program-level outcomes that students are expected to achieve, typically by the time they complete the degree program. Like the IGA section, each row may have: (1) an SO code (for example: SO1, SO2, SO3) that serves as a concise label; (2) an optional short title naming the outcome (some users leave this blank, which is acceptable); and (3) a description that states the outcome in full sentence form. Descriptions often follow formulations such as "Ability to analyze a complex computing problem and apply principles of computing and other relevant disciplines to identify solutions," describing what graduates can do in relation to their discipline. These SO codes and descriptions provide the bridge between institutional graduate attributes and course-level ILOs, and they are used as reference points when mapping ILOs, assessments, and learning activities to the program outcomes. When you summarize or restate the SO section, present it as a fixed markdown table with the header row "| Code | Title | Description |" followed by the alignment row "|:--|:--|:--|" and then one row per SO, placing the SO code, short title (if any), and full description in their respective columns.'
		),
		'cdio': (
			'The CDIO Framework Skills (CDIO) section identifies specific skills and capacities framed by the CDIO model (Conceive–Design–Implement–Operate) that students are expected to develop. Structurally, each row in this partial is similar to IGA: (1) a CDIO code (for example: CDIO1, CDIO2, CDIO3) that serves as a short label; (2) an optional title that names the skill cluster in a compact way (for example, "Disciplinary Knowledge and Reasoning"); and (3) a description that explains the skill in sentence form, such as "Knowledge of underlying mathematics and sciences, core disciplinary or engineering fundamentals, advanced disciplinary knowledge, methods, and tools." These CDIO codes, titles, and descriptions highlight discipline-specific knowledge and reasoning, personal and professional skills, interpersonal skills, and system building or operational abilities that the program wants to emphasize, and they provide a reference point when aligning course ILOs, learning activities, and assessments to CDIO-based expectations. When you summarize or restate the CDIO section, present it as a fixed markdown table with the header row "| Code | Title | Description |" followed by the alignment row "|:--|:--|:--|" and then one row per CDIO skill, placing the code, short title, and full description in their respective columns.'
		),
		'sdg': (
			'The Sustainable Development Goals (SDG) section records how the course connects to sustainability-related competencies and perspectives. Like the IGA section, each row typically has three parts: (1) an SDG-related code or label (for example: SDG1, SDG2, or a locally defined code); (2) a short title naming the competence or perspective in a compact way (for example, "Envisioning" or "Critical"); and (3) a description that explains what this competence means for learners. Descriptions often follow patterns such as: "Establish a link between long-term goals and immediate actions, and motivate people to take action by harnessing their deep aspirations" (for Envisioning), or "Examine economic, environmental, social, and cultural structures in the context of sustainable development, and challenge people to examine and question the underlying assumptions that influence their world views by having them reflect on unsustainable practices" (for Critical). Together, these SDG-related codes, titles, and descriptions indicate the kinds of sustainability thinking and action the course supports and provide a reference when aligning ILOs, learning activities, and assessments with SDG-oriented education. When you summarize or restate the SDG section, present it as a fixed markdown table with the header row "| Code | Title | Description |" followed by the alignment row "|:--|:--|:--|" and then one row per SDG-related entry, placing the code, short title, and full description in their respective columns.'
		),
		'tla-activities': (
			'The Teaching, Learning, and Assessment (TLA) Activities section lays out the week‑by‑week flow of the course. It is typically shown as a table with the columns "Ch.", "Topics / Reading List", "Wks.", "Topic Outcomes", "ILO", "SO", and "Delivery Method". The "Ch." column indicates the chapter number from the main textbook or reference. The "Topics / Reading List" column contains the main class topics and related classwork for that row (for example, a line like "Main Topic 1: Introduction to …" followed by separate lines such as "Assignment #1" and "Quiz #1"), with each item separated by a newline. The "Wks." column specifies the coverage of weeks for that topic or cluster of activities, which may be a single week (e.g., "2") or a range (e.g., "2–3" or "2–4"), depending on how the instructor schedules the content; the instructor decides the coverage, and the AI may propose reasonable ranges based on the total course weeks. The "Topic Outcomes" column lists what students should be able to do after that block of learning, usually as a series of short outcome statements (for example, describing, discussing, tracing, or analyzing key concepts in the topic). The "ILO" column records the ILO codes or numbers that are addressed by that row, based on the Intended Learning Outcomes and supported by how items in the Assessment Method and Distribution Map are distributed to those ILOs for the related tasks. The "SO" column records which Student Outcomes are most closely aligned with the topic and its ILOs. The "Delivery Method" column briefly describes how the learning for that row takes place (for example, combinations like "Face‑to‑face/Online Discussion, Videos, Practical Work, Module"). Orientation is usually scheduled at the start (often Week 1), midterm examinations are typically placed around Week 9, and final examinations or project submissions are often scheduled near the end of the term (for example, Week 17); those special rows may not require chapter, detailed topic outcomes, ILO, SO, or delivery method fields in the same way as regular topic rows. When you summarize or restate this section, you may mirror this structure using a markdown table with the same headers so that the flow of chapters, topics, weeks, outcomes, ILO/SO alignment, and delivery methods is clear at a glance.'
		),
		'assessment_schedule': (
			'The Assessment Schedule Mapping section links the specific assessment tasks to the weeks of the term. It is displayed as a two-part table: a "Distribution" column that lists each assessment method or task (for example, "Quiz 1", "Midterm Exam", "Project Submission"), and a set of week columns whose labels (such as "1", "2-3", "9", "17") are derived from the "Wks." values in the TLA Activities table. Each cell in the week grid can be marked with an "x" to indicate that the corresponding assessment is conducted in that week or week range. A row, therefore, shows one assessment method in the left column and, across the row, one or more "x" marks under the weeks when that method is scheduled. Weeks for which there is no assessment remain blank or use a placeholder such as "-". When you summarize or restate this section, present it as a markdown table where the first column is "Assessment Method" and the remaining columns are the visible week labels (for example, "Week 1", "Week 2-3", "Week 9", "Week 17"). Use a header row like "| Assessment Method | Week 1 | Week 2-3 | … |" with a matching alignment row of "|:--|:--|:--|…|", and then one row per assessment, marking scheduled weeks with "x" and leaving other week cells blank or with "-". This schedule should stay consistent with both the TLA Activities weeks and the Assessment Method and Distribution Map.'
		),
		'ilo_so_cpa_mapping': (
			'The ILO-SO-CPA Mapping section shows how each Intended Learning Outcome (ILO) is aligned with the Student Outcomes (SO) and with the Cognitive/Psychomotor/Affective (C/P/A) dimensions, using the assessment tasks as the link. The table has one row per ILO that actually participates in mappings, and columns for the ILO code, each active SO column, and the three CPA columns (C, P, A). For the SO cells, only the SOs that are meaningfully aligned with that ILO and its associated tasks are listed, based on the tasks, ILO codes, and SO codes that appear in the Teaching, Learning, and Assessment (TLA) Activities and in the Assessment Method and Distribution Map. Instead of repeating every task name here, each SO cell summarizes which tasks (by code or short label, such as "Q", "FE", "PRJ") from the distribution map contribute to that ILO–SO link (for example, a cell might show "FE, Q" under SO1 to indicate that both the Final Exam and Quizzes support that outcome). The C, P, and A columns record, for that ILO, the overall emphasis across Cognitive, Psychomotor, and Affective domains, again derived from how assessment tasks are distributed in the Assessment Method and Distribution Map. When you summarize or restate this section, use a fixed markdown table structure that starts with the header row "| ILO | SO1 | SO2 | … | C | P | A |" (using as many SO columns as are present) followed by an alignment row with ":--" for each column, then one row per ILO. In each row, list only the SOs and CPA values that truly apply to that ILO, so the mapping highlights the actual intersections between ILOs, Student Outcomes, and the assessment design.'
		),
		'ilo_iga_mapping': (
			'The ILO–IGA Mapping section shows how each Intended Learning Outcome (ILO) aligns with the Institutional Graduate Attributes (IGA), using the assessment tasks as evidence for the linkage. The table has one row per ILO and columns for the ILO code plus each active IGA column. For each IGA cell, list only the task codes or short labels (for example: "FE" for Final Exam, "ME" for Midterm Exam, "Q" for Quizzes, "PRJ" for Projects) that substantiate the alignment between that ILO and that IGA. These task codes should come from the Assessment Method and Distribution Map and the TLA Activities that tie tasks to ILOs. When you summarize or restate this section, present it as a fixed markdown table that starts with the header row "| ILO | IGA1 | IGA2 | … |" (with as many IGA columns as exist), followed by an alignment row with ":--" for each column, and then one row per ILO. Populate each IGA cell only with the task codes that genuinely support that ILO→IGA alignment; leave cells blank or use "-" if there is no demonstrated linkage.'
		),
		'ilo_cdio_sdg_mapping': (
			'The ILO–CDIO–SDG Mapping section shows how each Intended Learning Outcome (ILO) connects to CDIO skills and SDG competencies, again using the assessment tasks as evidence. The table has one row per ILO and two groups of columns: CDIO columns (CDIO1, CDIO2, …) and SDG columns (SDG1, SDG2, …). For each CDIO or SDG cell, list only the task codes or short labels (for example: "FE", "ME", "Q", "PRJ") that substantiate the alignment between that ILO and that CDIO or SDG entry, drawing from the Assessment Method and Distribution Map and the TLA Activities where tasks are tied to ILOs. When you summarize or restate this section, use a fixed markdown table that begins with the header row "| ILO | CDIO1 | CDIO2 | … | SDG1 | SDG2 | … |" (with as many CDIO and SDG columns as exist), followed by an alignment row with ":--" for each column, and then one row per ILO. In each CDIO/SDG cell, include only the task codes that truly demonstrate that alignment; leave cells blank or use "-" when no linkage is established.'
		)
	};

	function get(partialKey){
		if (!partialKey) return '';
		return PROMPTS[partialKey] || '';
	}

	function getAll(){
		// Return a shallow copy so callers cannot mutate our internal map
		return Object.assign({}, PROMPTS);
	}

	window.SVPrompts = { get, getAll };
})();

